apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: juandocker1/clip-cluster:celery
        env:
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: REDIS_URL
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AWS_SECRET_ACCESS_KEY
      imagePullSecrets:
      - name: regcred