    # Use an official Python runtime as a parent image
    FROM python:3.11.0-slim-buster

    # Set the working directory in the container to /app
    WORKDIR /app    

    # Install ffmpeg and yt-dlp
    RUN apt-get update && apt-get install -y ffmpeg
    RUN pip install yt-dlp flask gunicorn boto3 "celery[redis]"
    RUN apt-get clean

    # Copy the current directory contents into the container at /app
    COPY . /app
    
    CMD gunicorn -b 0.0.0.0:$PORT app:app
