apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  REDIS_URL: cmVkaXM6Ly86cDdhYzI3MmQ4OTQ3NjI0ZDg0MzQ3Njg5NGI5YTY2MjliODcxOTcwMTlkYTc4M2IxY2NjY2RlNjY4N2Q4ODkyM2NAZWMyLTQ2LTEzNy0xNzgtOTMuZXUtd2VzdC0xLmNvbXB1dGUuYW1hem9uYXdzLmNvbTo5NDU5
  AWS_SECRET_ACCESS_KEY: b0ExVTFrM2xaOHhzMlFneHBmYXBETDdqS055dU9zY1JTOU5ta2I2UXZzRQ==
